#######
# Compiled from data/tbg/functions/joined.mcscript
# to .//The Building Game/data/tbg/functions/joined/game.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s in_game matches 1 run gamemode creative @s
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg run function tbg:next/teleport
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 if score @s team matches 1.. run tag @s add tag2
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 if score @s team matches 1.. at @s as @e[tag=team] unless score @s stage = #stage tbg run function tbg:joined/game/team
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 if score @s team matches 1.. run tag @s remove tag2
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 unless score @s team matches 1.. at @s positioned ~-16 ~-9 ~-4 run clone -16 0 -16 15 31 15 ~ ~ ~
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 unless score @s team matches 1.. at @s positioned ~-16 ~-9 ~-4 run kill @e[type=!player,dx=30,dy=32,dz=30]
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 1 unless score @s team matches 1.. run function tbg:next/building/summon_field
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 0 if score @s team matches 1.. as @e[tag=team] unless score @s stage = #stage tbg run function tbg:next/writing/summon_team_bat
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 0 if score @s team matches 1.. as @e[tag=team] unless score @s stage = #stage tbg run scoreboard players operation @s stage = #stage tbg
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 0 unless score @s team matches 1.. run function tbg:next/writing/summon_bat
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg < #count id if score #odd tbg matches 0 run tag @e[type=bat,tag=rename,tag=!old] add new
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg >= #count id run scoreboard players set @s drop.sugar 0
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg >= #count id run scoreboard players set @s drop.redstone 0
execute if score @s in_game matches 1 unless score @s[team=players] stage = #stage tbg if score #stage tbg >= #count id run scoreboard players set @s drop.glowstone 0
execute if score @s in_game matches 1 run scoreboard players operation @s stage = #stage tbg
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 0 if score #stage tbg matches 0 run tellraw @s ["",{"translate":"Come up with a phrase","bold":true},"\n",{"translate":"Rename the name tag in the anvil into a word or phrase and use it on the bat."}]
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 0 if score #stage tbg matches 2.. run tellraw @s ["",{"translate":"Figure out what you see","bold":true},"\n",{"translate":"Look at this build and describe it by renaming the bat."}]
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 0 at @e[tag=renamed] if score @e[tag=renamed,distance=..0.01,limit=1] id = @s id run scoreboard players reset @s ready
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 1 run function tbg:next/building/message
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 1 run scoreboard players set #var joined 0
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 1 at @e[tag=field] if score @e[tag=field,distance=..0.01,limit=1] id = @s id run scoreboard players set #var joined 1
execute if score @s in_game matches 1 if score @s team matches 1.. if score #odd tbg matches 1 if score #var joined matches 0 run scoreboard players reset @s ready
execute unless score @s in_game matches 1 run team join spectators @s
execute unless score @s in_game matches 1 run scoreboard players set @s id 0
execute unless score @s in_game matches 1 run gamemode spectator @s
execute unless score @s in_game matches 1 run teleport @r[team=players]
scoreboard players reset @s accept
scoreboard players reset @s help
scoreboard players reset @s my_id
scoreboard players reset @s invite
scoreboard players reset @s kick
scoreboard players reset @s leave
scoreboard players reset @s time
scoreboard players reset @s ztbg_click