#######
# Compiled from data/tbg/functions/joined.mcscript
# to .//The Building Game/data/tbg/functions/joined/lobby.mcfunction
#
# Generated by Minecraft Script for 1.13
######
gamemode creative @s
execute positioned 0.0 64 0.0 run teleport @s[distance=96..] ~ ~ ~
function tbg:check_id
