#######
# Compiled from data/tbg/functions/joined.mcscript
# to .//The Building Game/data/tbg/functions/joined.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score #stage tbg matches 0.. run function tbg:joined/game

execute if score #stage tbg matches -2 run function tbg:joined/lobby

scoreboard players operation @s time = time options
scoreboard players set @s invite -2147483648
scoreboard players set @s kick -2147483648
scoreboard players reset @s joined
