#######
# Compiled from data/tbg/functions/player_init.mcscript
# to .//The Building Game/data/tbg/functions/player_init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add #count p_id 1
scoreboard players operation @s p_id = #count p_id
scoreboard players set @s invite -2147483648
scoreboard players set @s kick -2147483648
scoreboard players operation @s time = time options
clear @s
team join spectators @s
gamemode creative @s
teleport @s 0.0 64 0.0 0 0
execute if score #stage tbg matches 0.. run gamemode spectator @s
execute if score #stage tbg matches 0.. run teleport @r[team=players]
