#######
# Compiled from main/lobby/team/accept.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/accept.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score team_members options matches 0 run tellraw @s {"translate":"Teams are disabled","color":"red"}
execute unless score team_members options matches 0 unless score @s team.invite matches 1.. run tellraw @s {"translate":"You have no invites","color":"red"}
execute unless score team_members options matches 0 if score @s team.invite matches 1.. run scoreboard players operation #var team.invite = @s team.invite
execute unless score team_members options matches 0 if score @s team.invite matches 1.. as @a if score @s team = #var team.invite run tag @s add tag
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] run scoreboard players set #success tbg 1
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] as @a[tag=tag,limit=1] run function tbg:main/lobby/team/count_members
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score team_members options matches 2.. if score #count_members team >= team_members options run scoreboard players set #success tbg 0
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score team_members options matches 2.. if score #count_members team >= team_members options run tellraw @s {"translate":"The team that invited you has reached the maximum number of members","color":"red"}
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 if entity @s[team=!players] run function tbg:main/lobby/play/message
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run function tbg:main/lobby/team/_leave
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run scoreboard players operation @s pre-id = @a[tag=tag,limit=1] pre-id
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run function tbg:check_id
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run scoreboard players operation @s team = @s team.invite
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run tellraw @a[tag=tag] ["",{"selector":"@s"},{"translate":" joined your team"}]
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run tellraw @s ["",{"translate":"You joined the team {"},{"selector":"@a[tag=tag]"},{"translate":"}"}]
execute unless score team_members options matches 0 if score @s team.invite matches 1.. if entity @a[tag=tag] if score #success tbg matches 1 run scoreboard players reset @s team.invite
execute unless score team_members options matches 0 if score @s team.invite matches 1.. unless entity @a[tag=tag] run tellraw @s {"translate":"No members were found from the team invited you","color":"red"}
execute unless score team_members options matches 0 if score @s team.invite matches 1.. run tag @a remove tag
scoreboard players reset @s accept