#######
# Compiled from functions/main/lobby/team.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/actionbar.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main/lobby/team.mcscript
scoreboard players operation #var team = @s team
execute as @a if score @s team = #var team run tag @s add tag
title @a[tag=tag] actionbar ["",{"translate":"Your team: ","color":"gold","bold":true},{"selector":"@a[tag=tag]"}]
tag @a remove tag