#######
# Compiled from main/lobby/team/count_members.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/count_members.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation #var team = @s team
scoreboard players set #count_members team 0
execute as @a[scores={team=1..}] if score @s team = #var team run scoreboard players add #count_members team 1