#######
# Compiled from main/lobby/team/help.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/help.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s ["\n",{"translate":"Triggers:","color":"gold"},"\n",{"text":"accept","color":"yellow"},": ",{"translate":"Accept a team invite."},"\n",{"translate":"invite set <ID>","color":"yellow"},": ",{"translate":"Invite a player to your team."},"\n",{"translate":"kick set <ID>","color":"yellow"},": ",{"translate":"Kick a member from your team."},"\n",{"text":"leave","color":"yellow"},": ",{"translate":"Leave your team."},"\n",{"text":"my_id","color":"yellow"},": ",{"translate":"Find out your ID."},"\n",{"translate":"time (set|add) <seconds>","color":"yellow"},": ",{"translate":"Change the building time."},"\n"]
scoreboard players reset @s help