#######
# Compiled from main/lobby/team/invite.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/invite.create_team.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set #var team 0
scoreboard players operation #var team > @e[tag=team] team
scoreboard players add #var team 1
scoreboard players operation @s team = #var team
summon area_effect_cloud 0 0 0 {Tags:["team"],Duration:2147483647}
execute as @e[tag=team] unless score @s team matches 1.. run scoreboard players operation @s team = #var team