#######
# Compiled from main/lobby/team/kick.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/kick.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s kick matches -2147483647 run tellraw @s {"translate":"Usage: %s","color":"red","with":[{"translate":"\/trigger kick set <ID>"}]}
execute unless score @s kick matches -2147483647 unless score @s team matches 1.. run tellraw @s {"translate":"You\u2019re not a member of any team","color":"red"}
execute unless score @s kick matches -2147483647 if score @s team matches 1.. run scoreboard players operation #var kick = @s kick
execute unless score @s kick matches -2147483647 if score @s team matches 1.. as @a if score @s p_id = #var kick run tag @s add tag
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] unless score @a[tag=tag,limit=1] team = @s team run tellraw @s {"translate":"This player isn\u2019t in your team","color":"red"}
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team run tellraw @s ["",{"selector":"@a[tag=tag]"},{"translate":" was kicked from your team"}]
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team run tellraw @a[tag=tag] ["",{"selector":"@s"},{"translate":" kicked you from the team"}]
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team run tag @s add tag2
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=!tag2,tag=!tag] if score @s team = @a[tag=tag2,limit=1] team run tellraw @s ["",{"selector":"@a[tag=tag2]"},{"translate":" kicked "},{"selector":"@a[tag=tag]"},{"translate":" from the team"}]
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team run tag @s remove tag2
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=tag] run tag @s add tag2
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=tag] as @a[tag=!tag2] if score @s team = @a[tag=tag2,limit=1] team run tag @a remove tag2
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=tag] unless entity @s[tag=tag2] run function tbg:main/lobby/play/id
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=tag] run tag @s remove tag2
execute unless score @s kick matches -2147483647 if score @s team matches 1.. if entity @a[tag=tag] if score @a[tag=tag,limit=1] team = @s team as @a[tag=tag] run function tbg:main/lobby/team/_leave
execute unless score @s kick matches -2147483647 if score @s team matches 1.. unless entity @a[tag=tag] run tellraw @s {"translate":"No player was found","color":"red"}
execute unless score @s kick matches -2147483647 if score @s team matches 1.. run tag @a remove tag
scoreboard players set @s kick -2147483648