#######
# Compiled from main/lobby/team/leave.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/leave.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless score @s team matches 1.. run tellraw @s {"translate":"You\u2019re not a member of any team","color":"red"}

execute if score @s team matches 1.. run tellraw @s {"translate":"You left the team"}
execute if score @s team matches 1.. run tag @s add tag
execute if score @s team matches 1.. as @a[tag=!tag] if score @s team = @a[tag=tag,limit=1] team run tellraw @s ["",{"selector":"@a[tag=tag]","color":"yellow"},{"translate":" left your team"}]
execute if score @s team matches 1.. as @a[tag=!tag] if score @s team = @a[tag=tag,limit=1] team run tag @a remove tag
execute if score @s team matches 1.. unless entity @s[tag=tag] run function tbg:main/lobby/play/id
execute if score @s team matches 1.. run tag @s remove tag
execute if score @s team matches 1.. run function tbg:main/lobby/team/_leave

scoreboard players reset @s leave
