#######
# Compiled from main/lobby/team/my_id.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team/my_id.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s ["",{"translate":"Your ID: "},{"score":{"name":"@s","objective":"p_id"},"color":"gray"}]
scoreboard players reset @s my_id