#######
# Compiled from functions/main/building/floor.mcscript
# to .//The Building Game/data/tbg/functions/main/building/floor/replace/loop.x.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set #z.i tbg 0
execute at @e[tag=floor.clone] run function tbg:main/building/floor/replace/loop.z
tp @e[tag=floor.clone] ~1 ~ ~
scoreboard players add #x.i tbg 1
execute if score #x.i tbg matches ..17 at @e[tag=floor.clone] run function tbg:main/building/floor/replace/loop.x

