#######
# Compiled from functions/main/building/floor.mcscript
# to .//The Building Game/data/tbg/functions/main/building/floor/replace/loop.z.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clone -10 33 -13 -10 33 -13 ~ ~ ~
tp @e[tag=floor.clone] ~ ~ ~1
scoreboard players add #z.i tbg 1
execute if score #z.i tbg matches ..17 at @e[tag=floor.clone] run function tbg:main/building/floor/replace/loop.z
