#######
# Compiled from functions/main/lobby/viewer.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/viewer/loading/matches0.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main/lobby/viewer.mcscript
scoreboard players operation #load-z tbg = #save-z tbg
scoreboard players remove #load-z tbg 16