#######
# Compiled from functions/main/lobby/play.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/play/id.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add #count pre-id 1
scoreboard players operation @s pre-id = #count pre-id
function tbg:check_id
