#######
# Compiled from functions/main/lobby/play.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/play/message.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute at @s run playsound block.note_block.chime player @s ~ ~ ~ 1 0
title @s actionbar {"translate":"You joined the\u00a7e players"}
team join players @s