#######
# Compiled from functions/next/building/summon_team_field.mcscript
# to .//The Building Game/data/tbg/functions/next/building/summon_team_field/check.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @e[tag=tag] run function tbg:next/building/summon_field

tag @e[tag=tag] remove tag