#######
# Compiled from functions/next/building/summon_team_field.mcscript
# to .//The Building Game/data/tbg/functions/next/building/summon_team_field.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add tag
execute as @a[team=players,scores={team=1..}] if score @s team = @e[tag=tag,limit=1] team run function tbg:next/building/summon_team_field/check
tag @s remove tag
