#######
# Compiled from functions/next/building/summon_field.mcscript
# to .//The Building Game/data/tbg/functions/next/building/summon_field.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute at @s positioned ~2.5 ~ ~ run summon area_effect_cloud ~ ~ ~ {Duration:2147483647,Tags:["field"]}
execute at @s positioned ~2.5 ~ ~ run scoreboard players operation @e[tag=field,distance=..0.1] id = @s id
execute at @s positioned ~-2.5 ~-0.35 ~ run summon area_effect_cloud ~ ~ ~ {Duration:2147483647,CustomName:"{\"translate\":\"Floor Changer\"}",CustomNameVisible:1b,Tags:["floor"]}
execute at @s positioned ~-2.5 ~-0.35 ~ run clone ~ ~-0.65 ~ ~ ~-0.65 ~ ~ 1 ~