#######
# Compiled from functions/next/writing/summon_bat.mcscript
# to .//The Building Game/data/tbg/functions/next/writing/summon_bat_.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon bat ~ ~ ~ {NoGravity:1b,Invulnerable:1,NoAI:1,Silent:1,ActiveEffects:[{Id:11,Amplifier:5,Duration:2147483647,ShowParticles:0b}],Tags:["rename"],CustomName:"{\"translate\":\"Rename me!\"}"}
teleport @e[type=bat,tag=rename,distance=0] ~ ~ ~ facing entity @p[team=players] eyes
scoreboard players operation @e[type=bat,tag=rename,distance=0] id = @s id
scoreboard players operation @e[type=bat,tag=rename,distance=0] stage = #stage tbg
fill ~ ~-1 ~ ~-1 ~-1 ~ anvil[facing=west]
execute if score #stage tbg matches 0 run tag @e[type=bat,tag=rename,distance=0] add first
