#######
# Compiled from functions/next/writing/summon_bat.mcscript
# to .//The Building Game/data/tbg/functions/next/writing/summon_bat.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute at @s if score #stage tbg matches 1.. positioned ~ ~1 ~-2 run function tbg:next/writing/summon_bat_
execute at @s if score #stage tbg matches 0 positioned ~ ~1 ~3 run function tbg:next/writing/summon_bat_
