#######
# Compiled from data/tbg/functions/check_id.mcscript
# to .//The Building Game/data/tbg/functions/check_id/run/checked.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/check_id.mcscript
scoreboard players operation @s id = #check_id id
tag @s add checked