#######
# Compiled from tbg/functions/next/game_over.mcscript
# to .//The Building Game/data/tbg/functions/next/game_over.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @a {"translate":"Build recap has finished. Returning to the lobby..."}
scoreboard players reset * id
scoreboard players reset * pre-id
scoreboard players reset * in_game
scoreboard players reset * team
scoreboard players reset * team.invite
scoreboard players reset * ready
scoreboard players set @a invite -2147483648
scoreboard players set @a kick -2147483648
scoreboard players operation @a time = time options
execute if score team_members options matches 1.. run scoreboard objectives setdisplay belowName p_id

kill @e[tag=team]
team join spectators @a
scoreboard players set #count id 0
scoreboard players set #stage tbg -2
clear @a
gamemode creative @a
teleport @a 0.0 64 0.0 0 0