#######
# Compiled from tbg/functions/next/teleport.mcscript
# to .//The Building Game/data/tbg/functions/next/teleport.x.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score #var tbg matches 1.. run teleport @s ~32 ~ ~
execute if score #var tbg matches 1.. run scoreboard players remove #var tbg 1
execute if score #var tbg matches 1.. at @s run function tbg:next/teleport.x

