#######
# Compiled from tbg/functions/next/teleport.mcscript
# to .//The Building Game/data/tbg/functions/next/teleport.mcfunction
#
# Generated by Minecraft Script for 1.13
######
teleport @s 1024 64 0 0 0
execute if score #stage tbg <= #count id run scoreboard players operation #var tbg = @s id
execute if score #stage tbg <= #count id run scoreboard players operation #var tbg += #stage tbg
execute if score #stage tbg <= #count id if score #var tbg > #count id run scoreboard players operation #var tbg -= #count id
execute unless score #stage tbg <= #count id run scoreboard players operation #var tbg = #x tbg
execute at @s run function tbg:next/teleport.x
execute if score #stage tbg <= #count id run scoreboard players operation #var tbg = #stage tbg
execute if score #stage tbg <= #count id run scoreboard players add #var tbg 1
execute if score #stage tbg <= #count id run scoreboard players operation #var tbg /= #2 tbg
execute unless score #stage tbg <= #count id run scoreboard players operation #var tbg = #z tbg
execute at @s if score #var tbg matches 0 run teleport @s ~15.5 ~11 ~14
execute at @s if score #var tbg matches 1.. run teleport @s ~15.5 ~9 ~4
execute at @s run function tbg:next/teleport.z
