#######
# Compiled from main/lobby/options/start.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/start/team_members.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main/lobby/options/start.mcscript
function tbg:main/lobby/team/count_members
execute if score #count_members team > team_members options run scoreboard players set #success tbg 0
execute if score #count_members team > team_members options run scoreboard players operation #var team = @s team
execute if score #count_members team > team_members options run execute as @a[scores={team=1..}] if score @s team = #var team run tag @s add tag
execute if score #count_members team > team_members options run tellraw @a ["",{"translate":"The maximum number of members in the team {"},{"selector":"@a[tag=tag]"},{"translate":"} has been exceeded."}]
execute if score #count_members team > team_members options run tag @a remove tag
