#######
# Compiled from functions/main/lobby/viewer.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/viewer/loading.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block 1 41 -22 stone_button[powered=true] run scoreboard players add #load-z tbg 16
execute if block 1 41 -22 stone_button[powered=true] if score #load-z tbg > #save-z tbg run scoreboard players set #load-z tbg 16

execute if block -2 41 -22 stone_button[powered=true] run scoreboard players remove #load-z tbg 48
execute if block -2 41 -22 stone_button[powered=true] if score #load-z tbg matches ..0 run function tbg:main/lobby/viewer/loading/matches0

summon arrow 0 1 0 {xTile:992,yTile:64,zTile:0,Tags:["chunk_load"]}
summon arrow 0 1 0 {xTile:1008,yTile:64,zTile:0,Tags:["chunk_load"]}
execute as @e[tag=chunk_load,nbt={zTile:0}] store result entity @s zTile int 1 run scoreboard players get #load-z tbg
scoreboard players add #load-z tbg 16
summon arrow 0 1 0 {xTile:992,yTile:64,zTile:0,Tags:["chunk_load"]}
summon arrow 0 1 0 {xTile:1008,yTile:64,zTile:0,Tags:["chunk_load"]}
execute as @e[tag=chunk_load,nbt={zTile:0}] store result entity @s zTile int 1 run scoreboard players get #load-z tbg
summon area_effect_cloud 0 1 0 {Duration:2,Tags:["loading"]}
setblock 1 41 -22 air
setblock -2 41 -22 air
