#######
# Compiled from functions/main/lobby/viewer.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/viewer/loaded.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result entity @s Pos[0] double 1 run scoreboard players get #992 tbg
execute store result entity @s Pos[2] double 1 run scoreboard players get #load-z tbg
execute at @s positioned ~ 32 ~-16 run fill ~ ~-1 ~ ~ ~-2 ~ white_concrete
execute at @s positioned ~ 32 ~-16 run setblock ~ ~-1 ~ structure_block[mode=save]{name:"tbg:load",mode:"SAVE",posY:1,sizeX:32,sizeY:32,sizeZ:32,ignoreEntities:0b}
execute at @s positioned ~ 32 ~-16 run setblock ~ ~-2 ~ redstone_block
execute at @s positioned ~ 32 ~-16 run fill ~ ~-1 ~ ~ ~-2 ~ white_concrete
execute at @s positioned ~ 32 ~-16 as @e[tag=rename,distance=..1,limit=1] run tellraw @a[x=-16,y=32,z=-48,dx=31,dy=32,dz=31] ["\n",{"selector":"@s","color":"gold","bold":true},"\n",{"translate":"Ingenious: ","color":"gray"},{"score":{"objective":"drop.sugar","name":"@s"}}," ",{"translate":"Beautiful: ","color":"red"},{"score":{"objective":"drop.redstone","name":"@s"}}," ",{"translate":"Funny: ","color":"yellow"},{"score":{"objective":"drop.glowstone","name":"@s"}}]
execute positioned 15 32 -17 positioned ~-31 ~ ~-31 run kill @e[type=!player,dx=31,dy=32,dz=31]
execute positioned 15 32 -17 run fill ~ ~ ~ ~ ~1 ~ white_concrete
execute positioned 15 32 -17 run setblock ~ ~ ~ structure_block[mode=load]{name:"tbg:load",mode:"LOAD",ignoreEntities:0b,rotation:"CLOCKWISE_180"}
execute positioned 15 32 -17 run setblock ~ ~1 ~ redstone_block
setblock 1 40 -22 light_blue_concrete
setblock -2 40 -22 red_concrete
setblock 1 41 -22 stone_button[face=floor]
setblock -2 41 -22 stone_button[face=floor]
kill @s
kill @e[tag=chunk_load]