#######
# Compiled from functions/main/showing/vote.mcscript
# to .//The Building Game/data/tbg/functions/main/showing/vote.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[team=players] run function tbg:main/showing/vote/replaceitem
scoreboard players set @a[scores={drop.sugar=2..}] drop.sugar 0
scoreboard players set @a[scores={drop.redstone=2..}] drop.redstone 0
scoreboard players set @a[scores={drop.glowstone=2..}] drop.glowstone 0
kill @e[type=item,nbt={Item:{tag:{display:{Name:"{\"translate\":\"Ingenious\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}}}]
kill @e[type=item,nbt={Item:{tag:{display:{Name:"{\"translate\":\"Beautiful\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}}}]
kill @e[type=item,nbt={Item:{tag:{display:{Name:"{\"translate\":\"Funny\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}}}]
