#######
# Compiled from functions/next/showing/building.mcscript
# to .//The Building Game/data/tbg/functions/next/showing/building.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation #var tbg = @s id
execute at @s as @e[type=bat,tag=first] if score #var tbg = @s id run tellraw @a[team=players,distance=0] ["",{"translate":"Round complete","bold":true},"\n",{"translate":"Your phrase \u00ab"},{"selector":"@s","color":"gray"},{"translate":"\u00bb evolved into this build."}]