#######
# Compiled from functions/next/showing/save.mcscript
# to .//The Building Game/data/tbg/functions/next/showing/saved.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result entity @s Pos[0] double 1 run scoreboard players get #992 tbg
execute store result entity @s Pos[2] double 1 run scoreboard players get #save-z tbg
execute at @s positioned ~ 32 ~-16 run kill @e[type=!player,dx=30,dy=32,dz=30]
execute at @s positioned ~ 32 ~-16 run fill ~ ~ ~ ~ ~1 ~ white_concrete
execute at @s positioned ~ 32 ~-16 run setblock ~ ~ ~ structure_block[mode=load]{name:"tbg:save",mode:"LOAD",ignoreEntities:0b}
execute at @s positioned ~ 32 ~-16 run setblock ~ ~1 ~ redstone_block
kill @e[tag=chunk_load]
kill @s