#######
# Compiled from functions/next/showing/save.mcscript
# to .//The Building Game/data/tbg/functions/next/showing/saving.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute positioned ~ ~1 ~ run tag @e[distance=..0.1,tag=rename] add saved
execute at @s run fill ~ ~ ~ ~ ~-1 ~ white_concrete
execute at @s run setblock ~ ~ ~ structure_block[mode=save]{name:"tbg:save",mode:"SAVE",posY:1,sizeX:32,sizeY:32,sizeZ:32,ignoreEntities:0b}
execute at @s run setblock ~ ~-1 ~ redstone_block
execute at @s run fill ~ ~ ~ ~ ~-1 ~ white_concrete
summon arrow 0 1 0 {xTile:992,yTile:64,zTile:0,Tags:["chunk_load"]}
summon arrow 0 1 0 {xTile:1008,yTile:64,zTile:0,Tags:["chunk_load"]}
scoreboard players add #save-z tbg 16
execute as @e[tag=chunk_load,nbt={zTile:0}] store result entity @s zTile int 1 run scoreboard players get #save-z tbg
summon arrow 0 1 0 {xTile:992,yTile:64,zTile:0,Tags:["chunk_load"]}
summon arrow 0 1 0 {xTile:1008,yTile:64,zTile:0,Tags:["chunk_load"]}
scoreboard players add #save-z tbg 16
execute as @e[tag=chunk_load,nbt={zTile:0}] store result entity @s zTile int 1 run scoreboard players get #save-z tbg
data merge entity @s {Age:0}
tag @s add saving
