#######
# Compiled from data/tbg/functions/main.mcscript
# to .//The Building Game/data/tbg/functions/main/entity/init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main.mcscript
data merge entity @s {EggLayTime:2147483647,Fuse:32767s,NoAI:1,NoGravity:1,PersistenceRequired:1b,Silent:1b,ShowArms:1b,Invulnerable:1b,Health:0.001f,Attributes:[{Name:"generic.maxHealth",Base:0.001}]}
execute at @s run teleport @s ~ ~ ~ facing entity @p[team=players] eyes
tag @s add entity_init