#######
# Compiled from data/tbg/functions/main.mcscript
# to .//The Building Game/data/tbg/functions/main/entity.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main.mcscript
data merge entity @s {Fire:-20}
execute if entity @s[tag=!entity_init] run function tbg:main/entity/init
