#######
# Compiled from tbg/functions/main/lobby.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt=!{Dimension:"minecraft:overworld"}] in overworld run teleport @s 0.0 64 0.0 0 0
execute store result score #players tbg if entity @a[team=players]
execute if score #players tbg < #players-pre tbg run function tbg:check_id

scoreboard players operation #players-pre tbg = #players tbg
execute as @a run function tbg:main/lobby/triggers
function tbg:main/lobby/team
execute unless entity @e[tag=loading] run function tbg:main/lobby/viewer

execute as @e[tag=loading,nbt={Age:1}] run function tbg:main/lobby/viewer/loaded
execute as @a[x=-5.0,y=64.0,z=4.0,dx=2,dy=1,dz=2,team=!players] at @s run function tbg:main/lobby/play
execute as @a[x=2.0,y=64.0,z=4.0,dx=2,dy=1,dz=2,team=players] run function tbg:main/lobby/spectate_area
execute as @a unless score @s ztbg_click matches 0 run function tbg:main/lobby/options
execute as @a unless score @s time = time options run function tbg:main/lobby/options/time
scoreboard players reset @a[scores={sneaking=1..}] sneaking