#######
# Compiled from tbg/functions/main/showing.mcscript
# to .//The Building Game/data/tbg/functions/main/showing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt=!{Dimension:0}] in overworld run function tbg:next/teleport
execute as @e[tag=saving,nbt={Age:1}] run function tbg:next/showing/saved
effect clear @a invisibility
execute as @a[gamemode=creative] at @s positioned ^ ^ ^2.001 run effect give @a[distance=..2] invisibility 1 0 true
execute as @a[gamemode=creative] at @s if entity @a[distance=0.001..0.5] run effect give @s invisibility 1 0 true
execute as @e[tag=vote-saving,nbt={Age:1}] run function tbg:main/showing/vote-saved
replaceitem entity @a[team=players] hotbar.3 lingering_potion{CustomPotionColor:1363445,HideFlags:32,display:{Name:"{\"translate\":\"Next\\u00a77 (%s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.use\"}]}"}}
execute if score #odd tbg matches 1 run function tbg:main/showing/vote

execute if entity @e[type=potion,nbt={Potion:{tag:{display:{Name:"{\"translate\":\"Next\\u00a77 (%s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.use\"}]}"}}}}] run function tbg:main/showing/run

kill @e[type=item,nbt={Item:{tag:{display:{Name:"{\"translate\":\"Next\\u00a77 (%s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.use\"}]}"}}}}]