#######
# Compiled from data/tbg/functions/main.mcscript
# to .//The Building Game/data/tbg/functions/main/tnt.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main.mcscript
kill @s
summon creeper ~ ~ ~ {ExplosionRadius:3,Fuse:0}