#######
# Compiled from data/tbg/functions/main.mcscript
# to .//The Building Game/data/tbg/functions/main/waiting.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/main.mcscript
scoreboard players add #waiting tbg 1
execute if score #waiting tbg matches 30 run function tbg:check_id
execute if score #waiting tbg matches 30 run execute if score #count id matches 3.. run function tbg:next
execute if score #waiting tbg matches 30 run execute unless score #count id matches 3.. run teleport @a 0.0 64 0.0 0 0
execute if score #waiting tbg matches 30 run execute unless score #count id matches 3.. run tellraw @a {"translate":"You need at least %s players or teams to start the game.","with":[{"text":"3","color":"gold"}]}
execute if score #waiting tbg matches 30 run execute unless score #count id matches 3.. run scoreboard players set #stage tbg -2
