#######
# Compiled from tbg/functions/main/writing.mcscript
# to .//The Building Game/data/tbg/functions/main/writing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt=!{Dimension:"minecraft:overworld"}] in overworld run function tbg:next/teleport
execute as @a[team=spectators] at @s if entity @e[tag=renamed,tag=old,dx=-32,dy=-32,dz=-32] run title @s actionbar [{"translate":"You\u2019re looking at: "},{"selector":"@e[tag=renamed,tag=old,dx=-32,dy=-32,dz=-32]","color":"gold"}]
execute as @e[type=item,nbt={PickupDelay:40s,Item:{id:"minecraft:name_tag"}}] run data merge entity @s {PickupDelay:7,Thrower:{}}
execute if score #stage tbg matches 0 run title @a[team=players] actionbar {"translate":"Come up with a phrase"}

execute if score #stage tbg matches 2.. run title @a[team=players] actionbar {"translate":"Figure out what you see"}

execute as @e[tag=rename,tag=!renamed] at @s unless entity @s[nbt={CustomName:"{\"translate\":\"Rename me!\"}"}] as @a[team=players] if score @s id = @e[tag=rename,distance=0,limit=1] id run scoreboard players reset @s ready
execute as @e[tag=rename,tag=!renamed] at @s unless entity @s[nbt={CustomName:"{\"translate\":\"Rename me!\"}"}] as @a[team=players] if score @s id = @e[tag=rename,distance=0,limit=1] id run tellraw @a ["",{"selector":"@s"},{"translate":" is ready."}]
execute as @e[tag=rename,tag=!renamed] at @s unless entity @s[nbt={CustomName:"{\"translate\":\"Rename me!\"}"}] as @a at @s run playsound entity.ender_eye.death master @s ~ ~ ~
execute as @e[tag=rename,tag=!renamed] at @s unless entity @s[nbt={CustomName:"{\"translate\":\"Rename me!\"}"}] run tag @s add renamed
execute unless entity @e[type=bat,tag=rename,tag=!renamed] run function tbg:next
