#######
# Compiled from main/lobby/options/as_animation.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/as_animation.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add as_animation options 1
execute if score as_animation options matches 2.. run scoreboard players set as_animation options 0

execute if score as_animation options matches 1 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has enabled armor stands animation"}]

execute if score as_animation options matches 0 run replaceitem entity @a inventory.21 air
execute if score as_animation options matches 0 run replaceitem entity @a inventory.22 air
execute if score as_animation options matches 0 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has disabled armor stands animation"}]
