#######
# Compiled from main/lobby/options/as_customization.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/as_customization.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add as_customization options 1
execute if score as_customization options matches 2.. run scoreboard players set as_customization options 0

execute if score as_customization options matches 1 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has enabled armor stands customization"}]

execute if score as_customization options matches 0 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has disabled armor stands customization"}]
execute if score as_customization options matches 0 run replaceitem entity @a inventory.18 air
execute if score as_customization options matches 0 run replaceitem entity @a inventory.19 air
execute if score as_customization options matches 0 run replaceitem entity @a inventory.20 air
execute if score as_customization options matches 0 if score as_animation options matches 1 run replaceitem entity @a inventory.21 air
execute if score as_customization options matches 0 if score as_animation options matches 1 run replaceitem entity @a inventory.22 air
