#######
# Compiled from main/lobby/options/start.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/start.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score #count id matches ..2 run tellraw @a {"translate":"You need at least %s players or teams to start the game.","with":[{"text":"3","color":"gold"}]}
execute unless score #count id matches ..2 run scoreboard players set #success tbg 1
execute unless score #count id matches ..2 if score team_members options matches 2.. as @e[tag=team] run function tbg:main/lobby/options/start/team_members
execute unless score #count id matches ..2 if score #success tbg matches 1 run function tbg:check_id
execute unless score #count id matches ..2 if score #success tbg matches 1 run tellraw @a [{"text":"","bold":true},{"selector":"@s","color":"yellow"},{"translate":" started the game!"}]
execute unless score #count id matches ..2 if score #success tbg matches 1 run scoreboard players set #stage tbg 0
execute unless score #count id matches ..2 if score #success tbg matches 1 as @a[team=players] run function tbg:next/teleport
execute unless score #count id matches ..2 if score #success tbg matches 1 run scoreboard players set #waiting tbg 0
execute unless score #count id matches ..2 if score #success tbg matches 1 run scoreboard players set #stage tbg -1