#######
# Compiled from main/lobby/options/team_members.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/team_members.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score team_members options matches 0 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has enabled teams"}]
execute if score team_members options matches 0 run scoreboard objectives setdisplay below_name p_id

execute if score @s sneaking matches 1.. run scoreboard players remove team_members options 1
execute unless score @s sneaking matches 1.. run scoreboard players add team_members options 1
execute if score team_members options matches 11.. run scoreboard players set team_members options 0

execute if score team_members options matches ..-1 run scoreboard players set team_members options 10

execute if score team_members options matches 0 as @a[scores={team=1..}] run function tbg:main/lobby/options/team_members/leave
execute if score team_members options matches 0 run scoreboard players reset * team
execute if score team_members options matches 0 run scoreboard players reset * team.invite
execute if score team_members options matches 0 run kill @e[tag=team]
execute if score team_members options matches 0 run scoreboard objectives setdisplay below_name
execute if score team_members options matches 0 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has disabled teams"}]

execute if score team_members options matches 1 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set team members\u2019 limit to\u00a7a Unlimited"}]

execute if score team_members options matches 2.. run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set team members\u2019 limit to "},{"score":{"name":"team_members","objective":"options"},"color":"aqua"}]
