#######
# Compiled from main/lobby/options/time.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/time.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tbg:main/lobby/options/update
execute if score @s time matches ..0 if score time options matches 1.. run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set max building time to§a Unlimited"}]
execute if score @s time matches ..0 run scoreboard players set @s time 0

execute if score @s time matches 3600.. run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set max building time to "},{"score":{"name":"#h","objective":"time"},"color":"aqua"},{"translate":"h","color":"aqua"}," ",{"score":{"name":"#min","objective":"time"},"color":"aqua"},{"translate":"min","color":"aqua"}," ",{"score":{"name":"#s","objective":"time"},"color":"aqua"},{"translate":"s","color":"aqua"}]

execute if score @s time matches 60..3599 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set max building time to "},{"score":{"name":"#min","objective":"time"},"color":"aqua"},{"translate":"min","color":"aqua"}," ",{"score":{"name":"#s","objective":"time"},"color":"aqua"},{"translate":"s","color":"aqua"}]

execute if score @s time matches 1..59 run tellraw @a ["",{"selector":"@s","color":"yellow"},{"translate":" has set max building time to "},{"score":{"name":"#s","objective":"time"},"color":"aqua"},{"translate":"s","color":"aqua"}]

scoreboard players operation time options = @s time
scoreboard players operation @a time = time options