#######
# Compiled from main/lobby/options/update.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options/update.mcfunction
#
# Generated by Minecraft Script for 1.13
######
fill -2 66 7 1 64 7 air
setblock 1 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{color:"blue",messages:['[""]','{"text":"[Info]","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 8"}}','[""]','[""]']}}
setblock 1 65 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{color:"magenta",messages:['[""]','{"text":"[Start]","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set -800"}}','[""]','[""]']}}
execute if score @s time matches ..0 run setblock -1 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Time for"]','["building"]','{"text":"Unlimited","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 5"}}','[""]']}}

execute if score @s time matches 3600.. run scoreboard players operation #h time = @s time
execute if score @s time matches 3600.. run scoreboard players operation #h time /= #3600 tbg
execute if score @s time matches 3600.. run scoreboard players operation #min time = @s time
execute if score @s time matches 3600.. run scoreboard players operation #min time %= #3600 tbg
execute if score @s time matches 3600.. run scoreboard players operation #min time /= #60 tbg
execute if score @s time matches 3600.. run scoreboard players operation #s time = @s time
execute if score @s time matches 3600.. run scoreboard players operation #s time %= #60 tbg
execute if score @s time matches 3600.. run setblock -1 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Time for"]','["building"]','[{"score":{"name":"#h","objective":"time"},"color":"dark_aqua","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 5"}},"h ",{"score":{"name":"#min","objective":"time"}},"min ",{"score":{"name":"#s","objective":"time"}},"s"]','[""]']}}

execute if score @s time matches 60..3599 run scoreboard players operation #min time = @s time
execute if score @s time matches 60..3599 run scoreboard players operation #min time /= #60 tbg
execute if score @s time matches 60..3599 run scoreboard players operation #s time = @s time
execute if score @s time matches 60..3599 run scoreboard players operation #s time %= #60 tbg
execute if score @s time matches 60..3599 run setblock -1 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Time for"]','["building"]','[{"score":{"name":"#min","objective":"time"},"color":"dark_aqua","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 5"}},"min ",{"score":{"name":"#s","objective":"time"}},"s"]','[""]']}}

execute if score @s time matches 1..59 run scoreboard players operation #s time = @s time
execute if score @s time matches 1..59 run setblock -1 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Time for"]','["building"]','[{"score":{"name":"#s","objective":"time"},"color":"dark_aqua","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 5"}},"s"]','[""]']}}

execute if score _open_time options matches 1 run data modify block -1 66 7 front_text.messages[3] set value "{\"text\":\"[\\u2190 Back]\",\"color\":\"dark_red\"}"
execute if score _open_time options matches 1 run setblock -1 65 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{color:"blue",messages:['[""]','{"text":"[\\u00b110 seconds]","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 6"}}','[""]','[""]']}}
execute if score _open_time options matches 1 run setblock -2 65 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{color:"blue",messages:['[""]','{"text":"[\\u00b11 minute]","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 7"}}','[""]','[""]']}}
execute if score _open_time options matches 1 run setblock -2 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{color:"blue",messages:['[""]','{"text":"[Unlimited]","clickEvent":{"action":"run_command","value":"/trigger time set 0"}}','[""]','[""]']}}

execute if score _open_time options matches 0 if score as_customization options matches 1 run setblock -1 65 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Armor stands"]','["customization"]','[{"text":"Enabled \\u2714","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 3"}}]','[""]']}}
execute if score _open_time options matches 0 if score as_customization options matches 0 run setblock -1 65 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Armor stands"]','["customization"]','[{"text":"Disabled \\u2716","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 3"}}]','[""]']}}
execute if score _open_time options matches 0 run setblock -2 65 7 oak_wall_sign[facing=north]{is_waxed:1}

execute if score _open_time options matches 0 if score team_members options matches 0 run setblock -2 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Team"]','["members"]','[{"text":"No teams \\u2716","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 4"}}]','[""]']}}
execute if score _open_time options matches 0 if score team_members options matches 1 run setblock -2 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Team"]','["members"]','[{"text":"Unlimited","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 4"}}]','[""]']}}
execute if score _open_time options matches 0 if score team_members options matches 2.. run setblock -2 66 7 oak_wall_sign[facing=north]{is_waxed:1,front_text:{messages:['["Team"]','["members"]','[{"score":{"name":"team_members","objective":"options"},"color":"dark_aqua","clickEvent":{"action":"run_command","value":"/trigger ztbg_click set 4"}}]','[""]']}}
