#######
# Compiled from functions/main/lobby/options.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/options.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#as_animation
execute if score @s ztbg_click matches 2 if score as_customization options matches 1 run function tbg:main/lobby/options/as_animation

#as_customization
execute if score @s ztbg_click matches 3 run function tbg:main/lobby/options/as_customization

#team_members
execute if score @s ztbg_click matches 4 run function tbg:main/lobby/options/team_members

#time
execute if score @s ztbg_click matches 5 run function tbg:main/lobby/options/open_time

execute if score @s ztbg_click matches 6 if score @s sneaking matches 1.. run trigger time add -10
execute if score @s ztbg_click matches 6 unless score @s sneaking matches 1.. run trigger time add 10

execute if score @s ztbg_click matches 7 if score @s sneaking matches 1.. run trigger time add -60
execute if score @s ztbg_click matches 7 unless score @s sneaking matches 1.. run trigger time add 60

#info
execute if score @s ztbg_click matches 8 run tellraw @s ["\n",{"translate":"The Building Game","bold":true},"\n",{"translate":"Original idea: %s","with":[{"text":"SethBling","color":"gold"}]},"\n\n",{"translate":"Original 1.13 Release","bold":true},"\n",{"translate":"Map by: %s","with":[{"text":"Jerozgen","color":"gold"}]},"\n",{"translate":"Data packs:"},"\n ",{"text":"[AS Custom Poses and Animations]","color":"aqua","clickEvent":{"action":"open_url","value":"https://planetminecraft.com/project/customize-armor-stands-with-a-book"}}," ",{"translate":"(modified)","color":"gray"}," — ",{"text":"mc_da","color":"gold"},"\n ",{"text":"[ArmourStatuesV2.1]","color":"aqua","clickEvent":{"action":"open_url","value":"https://planetminecraft.com/project/armourstatuesv2-1-datapack"}}," ",{"translate":"(pose presets)","color":"gray"}," — ",{"text":"Phssthpok","color":"gold"},"\n",{"translate":"Thanks to: %s","with":[{"text":"Hovex, KindredTheFox, KrolixWormix, Krou","color":"gold"}]},"\n\n",{"translate":"This 1.20 Release","bold":true},"\n",{"translate":"Updated by: %s","with":[{"text":"DavePusey","color":"gold"}]},"\n",{"translate":"Data packs:"},"\n ",{"text":"[Armour Statues]","color":"aqua","clickEvent":{"action":"open_url","value":"https://vanillatweaks.net/picker/datapacks/"}}," ",{"translate":"(v2.8.11)","color":"gray"}," — ",{"text":"Vanilla Tweaks","color":"gold"},"\n\n",{"translate":"How to play","underlined":true},"\n",{"text":"","extra":[{"translate":"1. Come up with a word or phrase, rename a name tag and use it on the bat."},"\n",{"translate":"2. Build the phrase which was thought of by another player."},"\n",{"translate":"3. Describe the build which was built by another player."},"\n",{"translate":"4. Repeat step 2 and 3 until you change phrases of other players."}],"color":"gray"},"\n\n",{"translate":"Trigger help: %s","with":[{"translate":"[%s]","with":["/trigger help"],"color":"green","clickEvent":{"action":"run_command","value":"/trigger help"}}]},"\n"]

#start
execute if score @s ztbg_click matches -800 run function tbg:main/lobby/options/start

function tbg:main/lobby/options/update
scoreboard players reset @s ztbg_click