#######
# Compiled from functions/main/lobby/play.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/play.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tbg:main/lobby/play/message
function tbg:main/lobby/play/id
