#######
# Compiled from functions/main/lobby/spectate.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/spectate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
team join spectators @s
scoreboard players reset @s pre-id
scoreboard players reset @s id
function tbg:check_id
execute at @s run playsound block.note_block.bell player @s ~ ~ ~ 1 0
title @s actionbar {"translate":"You joined the\u00a77 spectators"}