#######
# Compiled from functions/main/lobby/team.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/team.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a unless score @s help matches 0 run function tbg:main/lobby/team/help
execute as @a unless score @s accept matches 0 run function tbg:main/lobby/team/accept
execute as @a unless score @s invite matches -2147483648 run function tbg:main/lobby/team/invite
execute as @a unless score @s kick matches -2147483648 run function tbg:main/lobby/team/kick
execute as @a unless score @s leave matches 0 run function tbg:main/lobby/team/leave
execute as @a unless score @s my_id matches 0 run function tbg:main/lobby/team/my_id
execute as @e[tag=team] run function tbg:main/lobby/team/actionbar