#######
# Compiled from functions/main/lobby/triggers.mcscript
# to .//The Building Game/data/tbg/functions/main/lobby/triggers.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players enable @s help
scoreboard players enable @s accept
scoreboard players enable @s my_id
scoreboard players enable @s invite
scoreboard players enable @s kick
scoreboard players enable @s leave
scoreboard players enable @s ztbg_click
scoreboard players enable @s time