#######
# Compiled from data/tbg/functions/check_id.mcscript
# to .//The Building Game/data/tbg/functions/check_id/run.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add #check_id id 1
scoreboard players set #var pre-id 2147483647
scoreboard players operation #var pre-id < @a[team=players,tag=!checked] pre-id
execute as @a[team=players,tag=!checked] if score @s pre-id = #var pre-id run function tbg:check_id/run/checked
execute if entity @a[team=players,tag=!checked] run function tbg:check_id/run
