#######
# Compiled from data/tbg/functions/joined.mcscript
# to .//The Building Game/data/tbg/functions/joined/game/team.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//The Building Game/data/tbg/functions/joined.mcscript
execute at @a[tag=tag2] positioned ~-16 ~-9 ~-4 run clone -16 0 -16 15 31 15 ~ ~ ~
execute at @a[tag=tag2] positioned ~-16 ~-9 ~-4 run kill @e[type=!player,dx=30,dy=32,dz=30]
function tbg:next/building/summon_team_field
scoreboard players set #var joined 1
execute at @e[type=bat,tag=!old,tag=new] run fill ~ ~-1 ~ ~-1 ~-1 ~ air replace anvil
scoreboard players operation @s stage = #stage tbg