#######
# Compiled from tbg/functions/main/building.mcscript
# to .//The Building Game/data/tbg/functions/main/building/found.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[team=players] if score @s id = @e[tag=field,distance=..0.1,limit=1] id run scoreboard players reset @s ready
execute as @a[team=players] if score @s id = @e[tag=field,distance=..0.1,limit=1] id run tellraw @a ["",{"selector":"@s"},{"translate":" is ready."}]
execute as @a at @s run playsound entity.ender_eye.death master @s ~ ~ ~
summon area_effect_cloud ~-18 ~-10 ~-4 {Duration:2147483647,Tags:["save"]}
setblock ~ ~1 ~ air
setblock ~ ~ ~ air
kill @s