#######
# Compiled from tbg/functions/main/building.mcscript
# to .//The Building Game/data/tbg/functions/main/building/message.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation #id_msg tbg = @s id
scoreboard players add #id_msg tbg 1
execute if score #id_msg tbg > #count id run scoreboard players set #id_msg tbg 1

execute at @s as @e[type=bat,tag=!old,tag=new] if score #id_msg tbg = @s id run title @a[team=players,distance=0] actionbar ["",{"translate":"Build: "},{"selector":"@s","color":"gold"}]
