#######
# Compiled from functions/main/building/timer.mcscript
# to .//The Building Game/data/tbg/functions/main/building/timer.mcfunction
#
# Generated by Minecraft Script for 1.13
######
bossbar set timer players @a
execute store result bossbar timer value run scoreboard players get #time tbg
execute if score #time tbg matches 3600.. run scoreboard players operation #display_time tbg = #time tbg
execute if score #time tbg matches 3600.. run scoreboard players operation #display_time tbg /= #3600 tbg
execute if score #time tbg matches 3600.. run bossbar set timer name ["",{"translate":"Time Remaining: "},{"score":{"objective":"tbg","name":"#display_time"},"color":"gold"},{"translate":"h"}]

execute if score #time tbg matches 60..3599 run scoreboard players operation #display_time tbg = #time tbg
execute if score #time tbg matches 60..3599 run scoreboard players operation #display_time tbg /= #60 tbg
execute if score #time tbg matches 60..3599 run bossbar set timer name ["",{"translate":"Time Remaining: "},{"score":{"objective":"tbg","name":"#display_time"},"color":"gold"},{"translate":"min"}]

execute if score #time tbg matches ..59 run scoreboard players operation #display_time tbg = #time tbg
execute if score #time tbg matches ..59 run scoreboard players operation #display_time tbg %= #60 tbg
execute if score #time tbg matches ..59 run bossbar set timer name ["",{"translate":"Time Remaining: "},{"score":{"objective":"tbg","name":"#display_time"},"color":"gold","bold":true},{"translate":"s"}]

execute if score #time tbg matches 60 run title @a times 0 40 10
execute if score #time tbg matches 60 run title @a title ""
execute if score #time tbg matches 60 run title @a subtitle {"translate":"%s seconds remaining","with":[{"text":"60","color":"yellow"}]}
execute if score #time tbg matches 60 at @a run playsound block.note_block.chime master @a ~ ~ ~ 2 1.3
execute if score #time tbg matches 60 run bossbar set timer max 60
execute if score #time tbg matches 60 run bossbar set timer style notched_6

execute if score #time tbg matches 30 run title @a times 0 40 10
execute if score #time tbg matches 30 run title @a title ""
execute if score #time tbg matches 30 run title @a subtitle {"translate":"%s seconds remaining","with":[{"text":"30","color":"yellow"}]}
execute if score #time tbg matches 30 at @a run playsound block.note_block.chime master @a ~ ~ ~ 2 1.3

execute if score #time tbg matches 10 run bossbar set timer max 10
execute if score #time tbg matches 10 run bossbar set timer style notched_10

execute if score #time tbg matches 1..10 run title @a times 0 10 10
execute if score #time tbg matches 1..10 run title @a title ""
execute if score #time tbg matches 1..10 run title @a subtitle {"score":{"objective":"tbg","name":"#display_time"},"color":"yellow"}
execute if score #time tbg matches 1..10 at @a run playsound block.note_block.chime master @a ~ ~ ~ 2 1.3

execute if score #time tbg matches ..0 run tellraw @a {"translate":"Time is up!","color":"gold"}
execute if score #time tbg matches ..0 run function tbg:next

scoreboard players set #ttime tbg 0
scoreboard players remove #time tbg 1