#######
# Compiled from functions/main/building/floor.mcscript
# to .//The Building Game/data/tbg/functions/main/building/floor/replace.mcfunction
#
# Generated by Minecraft Script for 1.13
######
fill ~-6 ~-2 ~6 ~11 ~-2 ~23 stone
summon area_effect_cloud ~-6 ~-2 ~6 {Tags:["floor.clone"]}
clone ~ ~ ~ ~ ~ ~ -10 33 -13
scoreboard players set #x.i tbg 0
execute at @e[tag=floor.clone] run function tbg:main/building/floor/replace/loop.x
