#######
# Compiled from functions/main/showing/vote.mcscript
# to .//The Building Game/data/tbg/functions/main/showing/vote/replaceitem.mcfunction
#
# Generated by Minecraft Script for 1.13
######
item replace entity @s[scores={drop.sugar=..0}] hotbar.5 with sugar{display:{Name:"{\"translate\":\"Ingenious\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}
item replace entity @s[scores={drop.redstone=..0}] hotbar.6 with redstone{display:{Name:"{\"translate\":\"Beautiful\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}
item replace entity @s[scores={drop.glowstone=..0}] hotbar.7 with glowstone_dust{display:{Name:"{\"translate\":\"Funny\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}
item replace entity @s[scores={drop.sugar=1..}] hotbar.5 with sugar{Enchantments:[{}],display:{Name:"{\"translate\":\"Ingenious\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}
item replace entity @s[scores={drop.redstone=1..}] hotbar.6 with redstone{Enchantments:[{}],display:{Name:"{\"translate\":\"Beautiful\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}
item replace entity @s[scores={drop.glowstone=1..}] hotbar.7 with glowstone_dust{Enchantments:[{}],display:{Name:"{\"translate\":\"Funny\\u00a77 (press %s)\",\"italic\":false,\"with\":[{\"keybind\":\"key.drop\"}]}"}}